# <center>CS568:Deep Learning</center>  <center>Spring 2020</center> 

## Pytorch Tutorial
Pytorch is a python framework for deep learning developed and maintained by Facebook 

- GPU-accelerated computations
- automatic differentiation
- modules for neural networks

This tutorial will teach you the fundamentals of operating on pytorch tensors and networks.

## Install Pytorch in virtual environment
What is virtual environment and why should we use?

Virtual environment is just like a container which contains libraries or packages. Each libray in this environment have its own dependencies, as opposed to being installed globally (in site-packages). 

**create virtual environment**

`conda create -n pytorch_env python`

**activate environment**

`activate pytorch_env`

**deactivate environment**

`deactivate pytorch_env`

**delete enviroment**

`conda remove -n pytorch_env --all`

**check environments list**

`conda info --envs`

**Install PyTorch**



In [2]:
import torch
import numpy as np
print("torch version:", torch.__version__) 

torch version: 1.2.0


**Tensor in Pytorch**

A tensor is an n-dimensional data container similar to the NumPy array. For example, 1d-tensor is a vector, 2d-tensor is a matrix, 3d-tensor is a cube, and 4d-tensor is a vector of cubes.

Construct a tensor with specific values

In [3]:
# creata a tensor
new_tensor = torch.Tensor([[1,2],[3,4]])
print(new_tensor) 
two_tensor = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(two_tensor)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
#create a 2 x 3 tensor with random values

rand_tensor = torch.rand(2, 3)
print(rand_tensor)

tensor([[0.4444, 0.4688, 0.9250],
        [0.1298, 0.8618, 0.8564]])


In [8]:
# create a 2 x 3 tensor with random values between -1 and 1

uniform_tensor = torch.Tensor(2, 3).uniform_(-1, 1)
print(uniform_tensor)

tensor([[ 0.1253, -0.6948, -0.5800],
        [ 0.1452,  0.8808, -0.3253]])


Construct a randomly initialized matrix.

In [9]:
# create a 2 x 3 tensor with random values from a uniform distribution [0, 1)
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

tensor([[0.6137, 0.9660, 0.7748],
        [0.4769, 0.1085, 0.3493]])


In [11]:
# create a 2 x 3 tensor of zeros
zero_tensor = torch.zeros(2, 3)
print(zero_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# create a 2 x 3 tensor of ones
one_tensor = torch.ones(2, 3)
print(one_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
# create an identity tensor
id_tensor = torch.eye(5)
print(id_tensor)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [17]:
# create a tensor from numpy
numpy_tensor = np.array([[1,2,3],[4,5,6]])
num_tensor = torch.from_numpy(numpy_tensor)
print(num_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [19]:
# create linearly spaced (evenly spaced numbers over a specified interval) tensors
lin_space_tensors = torch.linspace(0, 1, steps=5)
print(lin_space_tensors)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [9]:
# create logarithmically spaced (evenly spaced numbers on a log scale) tensors
log_space_tensors = torch.logspace(1, 3, steps=3)
print(log_space_tensors)

tensor([  10.,  100., 1000.])


In [10]:
# create a 1-d tensor with the values from start to end
ar_tensor = torch.arange(1, 10, step=2)
print(ar_tensor)

tensor([1, 3, 5, 7, 9])


In [26]:
new_tensor = torch.Tensor([[1, 2], [3, 4]])

# type of a tensor 
print(new_tensor.type())

# shape of a tensor
print(new_tensor.shape)
print(new_tensor.size())
print(new_tensor.dim())

torch.FloatTensor
torch.Size([2, 2])
torch.Size([2, 2])
2


In [28]:
# reshape a tensor using view command
print(new_tensor)
print(new_tensor.shape)

reshape_tensor = new_tensor.view(1,4)
print(reshape_tensor,reshape_tensor.shape)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor([[1., 2., 3., 4.]]) torch.Size([1, 4])


In [14]:
# concatenation operation 
a = torch.rand(1,2)
print(a, a.shape)
four_a = torch.cat((a,a,a,a),0)
print(four_a.size())
print(four_a)

tensor([[0.1440, 0.7441]]) torch.Size([1, 2])
torch.Size([4, 2])
tensor([[0.1440, 0.7441],
        [0.1440, 0.7441],
        [0.1440, 0.7441],
        [0.1440, 0.7441]])


In [19]:
# break a tensor into two parts
a = torch.rand(10,1)
print(a)
b = torch.chunk(a, 2, 0)
print(len(b))
print(b[0].size())
print(b)

tensor([[0.1927],
        [0.5255],
        [0.2501],
        [0.1954],
        [0.8005],
        [0.2370],
        [0.8250],
        [0.9187],
        [0.1040],
        [0.7343]])
2
torch.Size([5, 1])
(tensor([[0.1927],
        [0.5255],
        [0.2501],
        [0.1954],
        [0.8005]]), tensor([[0.2370],
        [0.8250],
        [0.9187],
        [0.1040],
        [0.7343]]))


In [20]:
# number of elements in a tensor
num_elements = torch.numel(a)
print(num_elements)

10


In [26]:
x = torch.rand([2,2])
print(x)

# concatenate
con_x = torch.cat((x,x),0)
print(con_x.shape, con_x)

tensor([[0.3322, 0.6444],
        [0.5926, 0.6331]])
torch.Size([4, 2]) tensor([[0.3322, 0.6444],
        [0.5926, 0.6331],
        [0.3322, 0.6444],
        [0.5926, 0.6331]])


In [28]:
# select some indices values using Index select
t = torch.Tensor([[1,2],[3,4],[5,6]])
indices = torch.LongTensor([0])
ind_select = torch.index_select(t, 1, indices) # select from dim 1
print(ind_select)

tensor([[1.],
        [3.],
        [5.]])


In [37]:
# Masked select
t = torch.Tensor([[1,2],[3,4],[5,6]])
mask = t.ge(2) #greater than
masked_select = torch.masked_select(t,mask)
print(masked_select)

tensor([2., 3., 4., 5., 6.])


In [30]:
# Get indices of non-zero elements 
t = torch.Tensor([[1,0],[0,0],[0,6]])
non_zero_val_indices = torch.nonzero(t)
print(non_zero_val_indices)

tensor([[0, 0],
        [2, 1]])


In [31]:
# Squeeze and unsqueeze
t = torch.ones(2,1,2,1) # Size 2x1x2x1
sq_t = torch.squeeze(t)     # Size 2x2
sq_t1 = torch.squeeze(t, 1)  # Squeeze dimension 1: Size 2x2x1
print(t.shape,sq_t.shape,sq_t1.shape)

# Un-squeeze a dimension
usq_t1 = torch.unsqueeze(sq_t1, 0)       
print(usq_t1.shape)

torch.Size([2, 1, 2, 1]) torch.Size([2, 2]) torch.Size([2, 2, 1])
torch.Size([1, 2, 2, 1])


In [51]:
# transpose of a matrix
mat = torch.rand([2,3])
print(mat)
mat_t = torch.t(mat)
print(mat_t)

tensor([[0.6747, 0.9334, 0.3276],
        [0.6026, 0.2177, 0.7325]])
tensor([[0.6747, 0.6026],
        [0.9334, 0.2177],
        [0.3276, 0.7325]])


In [42]:
# Basic Math operations

a = torch.Tensor([-2, -4, 8])
abs_a = torch.abs(a) 
print(a)
print(abs_a)

# Add x, y and scalar 10 to all elements
add_a = torch.add(abs_a, 10)
print(add_a)

# Clamp the value of a Tensor
rand_t = torch.rand(2,2)*3
clam_t = torch.clamp(rand_t, min=0.5, max=2)
print("random ", rand_t)
print("clamp ", clam_t)

# Element-wise divide
ele_div = torch.div(abs_a, 2)
print(ele_div)

tensor([-2., -4.,  8.])
tensor([2., 4., 8.])
tensor([12., 14., 18.])
random  tensor([[2.0088, 1.4708],
        [1.3292, 0.6305]])
clamp  tensor([[2.0000, 1.4708],
        [1.3292, 0.6305]])
tensor([1., 2., 4.])


In [54]:
# To sum all elements of a tensor
t = torch.Tensor([[2,2],[2,2]])
sum_t = torch.sum(t) # gives back a scalar
print(sum_t)
mean_t = torch.mean(t)
print(mean_t)

# To sum over all columns
t = torch.Tensor([[1,4],[2,3]])
sum1_t = torch.sum(t, dim=0) 
print(sum1_t)

# To sum over all rows
sum2_t = torch.sum(t, dim=1) 
print(sum2_t)

tensor(8.)
tensor(2.)
tensor([3., 7.])
tensor([5., 5.])


In [55]:
### Comparison
a = torch.Tensor([[1,2],[2,2]])
b = torch.Tensor([[1,2],[3,3]])
                  

# Element-wise comparison
comp = torch.eq(a, b)
print(comp)

tensor([[ True,  True],
        [False, False]])


In [78]:
# dot product of two tensors
a = torch.Tensor([1,3])
b = torch.Tensor([2,4])
dot_product = torch.dot(a,b)
print(dot_product)

tensor(14.)


In [59]:
# matrix vector multiplication
mat = torch.randn(2, 4)
vec = torch.randn(4)
res_mv = torch.mv(mat, vec)
print(mat)
print(vec)
print(res_mv)

tensor([[-0.6534, -1.2370, -0.8502, -0.8608],
        [-0.2538,  0.8644,  1.0236, -1.0044]])
tensor([-1.4752, -0.5753,  0.7847,  0.6989])
tensor([ 0.4067, -0.0216])


In [81]:
# matrix matrix multiplication
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 4)
res_mm = torch.mm(mat1, mat2)
print(res_mm)

tensor([[-0.9649, -0.0073, -0.0550, -0.0107],
        [ 1.1301,  0.6311,  0.3516,  1.0036]])


In [83]:
# Outer product of 2 vectors
v1 = torch.arange(1, 4)     # size 3
v2 = torch.arange(1, 3)     # size 2
print(v1,v2)
r = torch.ger(v1, v2) # 3x2
print(r)

tensor([1, 2, 3]) tensor([1, 2])
tensor([[1, 2],
        [2, 4],
        [3, 6]])
